/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE: () => VIEW_TYPE,
  default: () => HeadingWordCountPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// counter.ts
var DEFAULT_COUNT_OPTIONS = {
  countChinesePunctuation: false,
  excludeCodeBlocks: true,
  excludeInlineCode: true
};
var CJK_CHARS = /[㐀-䶿一-鿿豈-﫿぀-ゟ゠-ヿ가-힯]/g;
var CJK_PUNCT = /[、-〿︐-︙︰-﹏！-／：-＠［-｀｛-､–—‘’“”…]/g;
var LATIN_WORD = /[0-9A-Za-zÀ-ɏͰ-ϿЀ-ӿ０-９Ａ-Ｚａ-ｚ]+(?:['’’\-][0-9A-Za-zÀ-ɏͰ-ϿЀ-ӿ０-９Ａ-Ｚａ-ｚ]+)*/g;
var ATX_HEADING = /^(#{1,6})\s+(.*\S)\s*$/;
var BARE_URL = /https?:\/\/[^\s)]+/g;
function cleanForCounting(text, opts) {
  let t = text;
  t = t.replace(/%%[\s\S]*?%%/g, " ");
  t = t.replace(/<!--[\s\S]*?-->/g, " ");
  if (opts.excludeInlineCode) {
    t = t.replace(/`[^`]*`/g, " ");
  }
  t = t.replace(/!\[[^\]]*\]\([^)]*\)/g, " ");
  t = t.replace(/!\[\[[^\]]*\]\]/g, " ");
  t = t.replace(/\[\[([^\]|]*)\|([^\]]*)\]\]/g, "$2");
  t = t.replace(/\[\[([^\]]*)\]\]/g, "$1");
  t = t.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  t = t.replace(BARE_URL, " ");
  return t;
}
function countText(text, opts) {
  const cleaned = cleanForCounting(text, opts);
  const cjk = (cleaned.match(CJK_CHARS) || []).length;
  const punct = opts.countChinesePunctuation ? (cleaned.match(CJK_PUNCT) || []).length : 0;
  const latin = (cleaned.match(LATIN_WORD) || []).length;
  return cjk + punct + latin;
}
function stripFrontmatter(lines) {
  if (lines.length > 0 && lines[0].trim() === "---") {
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].trim() === "---") {
        return lines.slice(i + 1);
      }
    }
  }
  return lines;
}
function cleanHeadingTitle(raw) {
  let t = raw.replace(/\s+#+\s*$/, "");
  t = t.replace(/`([^`]*)`/g, "$1");
  t = t.replace(/\[\[([^\]|]*)\|([^\]]*)\]\]/g, "$2");
  t = t.replace(/\[\[([^\]]*)\]\]/g, "$1");
  t = t.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  t = t.replace(/(\*\*|__|\*|_|~~|==)/g, "");
  return t.trim();
}
function analyzeDocument(content, opts) {
  const rawLines = content.split(/\r?\n/);
  const lines = stripFrontmatter(rawLines);
  const lineOffset = rawLines.length - lines.length;
  const rawHeadings = [];
  let current = null;
  const preamble = [];
  let inFence = false;
  let fenceMarker = "";
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    const fenceMatch = trimmed.match(/^(`{3,}|~{3,})/);
    if (fenceMatch) {
      const marker = fenceMatch[1][0];
      if (!inFence) {
        inFence = true;
        fenceMarker = marker;
      } else if (marker === fenceMarker) {
        inFence = false;
        fenceMarker = "";
      }
      if (!opts.excludeCodeBlocks) {
        (current ? current.bodyLines : preamble).push(line);
      }
      continue;
    }
    if (inFence) {
      if (!opts.excludeCodeBlocks) {
        (current ? current.bodyLines : preamble).push(line);
      }
      continue;
    }
    const h = line.match(ATX_HEADING);
    if (h) {
      current = {
        level: h[1].length,
        title: cleanHeadingTitle(h[2]),
        line: i + lineOffset,
        bodyLines: []
      };
      rawHeadings.push(current);
      continue;
    }
    (current ? current.bodyLines : preamble).push(line);
  }
  const headings = rawHeadings.map((r) => ({
    level: r.level,
    title: r.title,
    line: r.line,
    ownCount: countText(r.bodyLines.join("\n"), opts),
    totalCount: 0
  }));
  for (let i = 0; i < headings.length; i++) {
    let sum = headings[i].ownCount;
    for (let j = i + 1; j < headings.length; j++) {
      if (headings[j].level <= headings[i].level)
        break;
      sum += headings[j].ownCount;
    }
    headings[i].totalCount = sum;
  }
  const bodyOnly = countText(preamble.join("\n"), opts);
  const documentTotal = bodyOnly + headings.reduce((acc, h) => acc + h.ownCount, 0);
  return { headings, documentTotal };
}

// main.ts
var VIEW_TYPE = "heading-word-count-outline";
var DEFAULT_SETTINGS = {
  ...DEFAULT_COUNT_OPTIONS,
  countMode: "total",
  showDocumentTotal: true,
  maxDepth: 6
};
var HeadingWordCountPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new HeadingWordCountView(leaf, this));
    this.addRibbonIcon("list-ordered", "\u5B57\u6578\u5927\u7DB1", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-heading-word-count-outline",
      name: "\u958B\u555F\u5B57\u6578\u5927\u7DB1\u9762\u677F",
      callback: () => this.activateView()
    });
    this.addSettingTab(new HeadingWordCountSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.refreshViews())
    );
    this.registerEvent(
      this.app.workspace.on("file-open", () => this.refreshViews())
    );
    const debouncedRefresh = (0, import_obsidian.debounce)(() => this.refreshViews(), 400, false);
    this.registerEvent(
      this.app.workspace.on("editor-change", () => debouncedRefresh())
    );
    this.app.workspace.onLayoutReady(() => this.refreshViews());
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshViews();
  }
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof HeadingWordCountView)
        view.render();
    });
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (!right)
        return;
      leaf = right;
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
};
var HeadingWordCountView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "\u5B57\u6578\u5927\u7DB1";
  }
  getIcon() {
    return "list-ordered";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  getActiveMarkdownFile() {
    const active = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (active && active.file)
      return active.file;
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const v = leaf.view;
      if (v instanceof import_obsidian.MarkdownView && v.file)
        return v.file;
    }
    return null;
  }
  render() {
    const container = this.contentEl;
    container.empty();
    container.addClass("hwc-view");
    const file = this.getActiveMarkdownFile();
    if (!file) {
      container.createDiv({
        cls: "hwc-empty",
        text: "\u958B\u555F\u4E00\u4EFD Markdown \u7B46\u8A18\u4EE5\u986F\u793A\u5B57\u6578\u5927\u7DB1\u3002"
      });
      return;
    }
    const activeMd = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeMd && activeMd.file === file) {
      this.renderContent(file, activeMd.editor.getValue());
    } else {
      this.app.vault.cachedRead(file).then((content) => {
        this.renderContent(file, content);
      });
    }
  }
  renderContent(file, content) {
    const container = this.contentEl;
    container.empty();
    const data = analyzeDocument(content, this.plugin.settings);
    const s = this.plugin.settings;
    const header = container.createDiv({ cls: "hwc-header" });
    header.createDiv({ cls: "hwc-filename", text: file.basename });
    if (s.showDocumentTotal) {
      header.createDiv({
        cls: "hwc-doctotal",
        text: `\u5168\u6587 ${formatCount(data.documentTotal)} \u5B57`
      });
    }
    const visible = data.headings.filter((h) => h.level <= s.maxDepth);
    if (visible.length === 0) {
      container.createDiv({
        cls: "hwc-empty",
        text: "\u9019\u4EFD\u7B46\u8A18\u6C92\u6709\u6A19\u984C (H1\u2013H6)\u3002"
      });
      return;
    }
    const list = container.createDiv({ cls: "hwc-list" });
    for (const h of visible) {
      const count = s.countMode === "total" ? h.totalCount : h.ownCount;
      const row = list.createDiv({ cls: `hwc-row hwc-h${h.level}` });
      row.style.paddingLeft = `${(h.level - 1) * 14 + 4}px`;
      row.createSpan({
        cls: "hwc-title",
        text: h.title || "(\u7121\u6A19\u984C)"
      });
      row.createSpan({
        cls: "hwc-badge",
        text: formatCount(count)
      });
      row.addEventListener("click", () => this.revealHeading(file, h.line));
    }
  }
  revealHeading(file, line) {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    let target = null;
    for (const leaf of leaves) {
      const v = leaf.view;
      if (v instanceof import_obsidian.MarkdownView && v.file === file) {
        target = leaf;
        break;
      }
    }
    const open = target ? Promise.resolve(target) : this.app.workspace.getLeaf(false).openFile(file).then(() => {
      const l = this.app.workspace.getMostRecentLeaf();
      return l;
    });
    Promise.resolve(open).then((leaf) => {
      if (!leaf)
        return;
      this.app.workspace.revealLeaf(leaf);
      const view = leaf.view;
      if (view instanceof import_obsidian.MarkdownView) {
        const editor = view.editor;
        editor.setCursor({ line, ch: 0 });
        editor.scrollIntoView(
          { from: { line, ch: 0 }, to: { line, ch: 0 } },
          true
        );
        editor.focus();
      }
    });
  }
};
function formatCount(n) {
  return n.toLocaleString("en-US");
}
var HeadingWordCountSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u8A08\u7B97\u7BC4\u570D").setDesc(
      "\u6BCF\u500B\u6A19\u984C\u7684\u5B57\u6578\u8981\u300C\u5305\u542B\u5E95\u4E0B\u6240\u6709\u5B50\u7AE0\u7BC0\u300D\uFF0C\u9084\u662F\u300C\u53EA\u7B97\u5230\u4E0B\u4E00\u500B\u6A19\u984C\u4E4B\u524D\u300D\u3002"
    ).addDropdown(
      (d) => d.addOption("total", "\u542B\u5B50\u7AE0\u7BC0\uFF08H1 \u5305\u542B\u5176\u4E0B\u6240\u6709\u5167\u5BB9\uFF09").addOption("own", "\u53EA\u7B97\u672C\u7BC0\uFF08\u4E0D\u542B\u5B50\u7AE0\u7BC0\uFF09").setValue(this.plugin.settings.countMode).onChange(async (v) => {
        this.plugin.settings.countMode = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8A08\u5165\u4E2D\u6587\u6A19\u9EDE\u7B26\u865F").setDesc(
      "\u958B\u555F\u5F8C\uFF0C\u4E2D\u6587\u6A19\u9EDE\uFF08\uFF0C\u3002\u3001\uFF01\uFF1F\u300C\u300D\u7B49\uFF09\u4E5F\u6703\u8A08\u70BA 1 \u500B\u5B57\u3002\u4E2D\u6587\u65B9\u584A\u5B57\u4E00\u5F8B\u9010\u5B57\u8A08\u7B97\uFF0C\u4E0D\u53D7\u6B64\u9805\u5F71\u97FF\u3002"
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.countChinesePunctuation).onChange(async (v) => {
        this.plugin.settings.countChinesePunctuation = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6392\u9664\u7A0B\u5F0F\u78BC\u5340\u584A").setDesc("\u4E0D\u8A08\u7B97 ``` \u570D\u6B04\u7A0B\u5F0F\u78BC\u5340\u584A\u5167\u7684\u6587\u5B57\u3002").addToggle(
      (t) => t.setValue(this.plugin.settings.excludeCodeBlocks).onChange(async (v) => {
        this.plugin.settings.excludeCodeBlocks = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6392\u9664\u884C\u5167\u7A0B\u5F0F\u78BC").setDesc("\u4E0D\u8A08\u7B97 `\u884C\u5167\u7A0B\u5F0F\u78BC` \u5167\u7684\u6587\u5B57\u3002").addToggle(
      (t) => t.setValue(this.plugin.settings.excludeInlineCode).onChange(async (v) => {
        this.plugin.settings.excludeInlineCode = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u986F\u793A\u5230\u7B2C\u5E7E\u5C64\u6A19\u984C").setDesc("\u53EA\u5728\u9762\u677F\u4E2D\u986F\u793A\u5230\u6307\u5B9A\u5C64\u7D1A\u7684\u6A19\u984C\uFF081 = \u53EA\u986F\u793A H1\uFF0C6 = \u5168\u90E8\u986F\u793A\uFF09\u3002").addSlider(
      (sl) => sl.setLimits(1, 6, 1).setValue(this.plugin.settings.maxDepth).setDynamicTooltip().onChange(async (v) => {
        this.plugin.settings.maxDepth = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u986F\u793A\u5168\u6587\u7E3D\u5B57\u6578").setDesc("\u5728\u9762\u677F\u9802\u7AEF\u986F\u793A\u6574\u4EFD\u7B46\u8A18\u7684\u7E3D\u5B57\u6578\u3002").addToggle(
      (t) => t.setValue(this.plugin.settings.showDocumentTotal).onChange(async (v) => {
        this.plugin.settings.showDocumentTotal = v;
        await this.plugin.saveSettings();
      })
    );
  }
};
