/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE: () => VIEW_TYPE,
  default: () => HeadingWordCountPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// counter.ts
var DEFAULT_COUNT_OPTIONS = {
  countChinesePunctuation: false,
  excludeCodeBlocks: true,
  excludeInlineCode: true
};
var CJK_CHARS = /[㐀-䶿一-鿿豈-﫿぀-ゟ゠-ヿ가-힯]/g;
var CJK_PUNCT = /[、-〿︐-︙︰-﹏！-／：-＠［-｀｛-､–—‘’“”…]/g;
var LATIN_WORD = /[0-9A-Za-zÀ-ɏͰ-ϿЀ-ӿ０-９Ａ-Ｚａ-ｚ]+(?:['‘’-][0-9A-Za-zÀ-ɏͰ-ϿЀ-ӿ０-９Ａ-Ｚａ-ｚ]+)*/g;
var ATX_HEADING = /^(#{1,6})\s+(.*\S)\s*$/;
var BARE_URL = /https?:\/\/[^\s)]+/g;
function cleanForCounting(text, opts) {
  let t = text;
  t = t.replace(/%%[\s\S]*?%%/g, " ");
  t = t.replace(/<!--[\s\S]*?-->/g, " ");
  if (opts.excludeInlineCode) {
    t = t.replace(/`[^`]*`/g, " ");
  }
  t = t.replace(/!\[[^\]]*\]\([^)]*\)/g, " ");
  t = t.replace(/!\[\[[^\]]*\]\]/g, " ");
  t = t.replace(/\[\[([^\]|]*)\|([^\]]*)\]\]/g, "$2");
  t = t.replace(/\[\[([^\]]*)\]\]/g, "$1");
  t = t.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  t = t.replace(BARE_URL, " ");
  return t;
}
function countText(text, opts) {
  const cleaned = cleanForCounting(text, opts);
  const cjk = (cleaned.match(CJK_CHARS) || []).length;
  const punct = opts.countChinesePunctuation ? (cleaned.match(CJK_PUNCT) || []).length : 0;
  const latin = (cleaned.match(LATIN_WORD) || []).length;
  return cjk + punct + latin;
}
function stripFrontmatter(lines) {
  if (lines.length > 0 && lines[0].trim() === "---") {
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].trim() === "---") {
        return lines.slice(i + 1);
      }
    }
  }
  return lines;
}
function cleanHeadingTitle(raw) {
  let t = raw.replace(/\s+#+\s*$/, "");
  t = t.replace(/`([^`]*)`/g, "$1");
  t = t.replace(/\[\[([^\]|]*)\|([^\]]*)\]\]/g, "$2");
  t = t.replace(/\[\[([^\]]*)\]\]/g, "$1");
  t = t.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  t = t.replace(/(\*\*|__|\*|_|~~|==)/g, "");
  return t.trim();
}
function analyzeDocument(content, opts) {
  const rawLines = content.split(/\r?\n/);
  const lines = stripFrontmatter(rawLines);
  const lineOffset = rawLines.length - lines.length;
  const rawHeadings = [];
  let current = null;
  const preamble = [];
  let inFence = false;
  let fenceMarker = "";
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    const fenceMatch = trimmed.match(/^(`{3,}|~{3,})/);
    if (fenceMatch) {
      const marker = fenceMatch[1][0];
      if (!inFence) {
        inFence = true;
        fenceMarker = marker;
      } else if (marker === fenceMarker) {
        inFence = false;
        fenceMarker = "";
      }
      if (!opts.excludeCodeBlocks) {
        (current ? current.bodyLines : preamble).push(line);
      }
      continue;
    }
    if (inFence) {
      if (!opts.excludeCodeBlocks) {
        (current ? current.bodyLines : preamble).push(line);
      }
      continue;
    }
    const h = line.match(ATX_HEADING);
    if (h) {
      current = {
        level: h[1].length,
        title: cleanHeadingTitle(h[2]),
        line: i + lineOffset,
        bodyLines: []
      };
      rawHeadings.push(current);
      continue;
    }
    (current ? current.bodyLines : preamble).push(line);
  }
  const headings = rawHeadings.map((r) => ({
    level: r.level,
    title: r.title,
    line: r.line,
    ownCount: countText(r.bodyLines.join("\n"), opts),
    totalCount: 0
  }));
  for (let i = 0; i < headings.length; i++) {
    let sum = headings[i].ownCount;
    for (let j = i + 1; j < headings.length; j++) {
      if (headings[j].level <= headings[i].level)
        break;
      sum += headings[j].ownCount;
    }
    headings[i].totalCount = sum;
  }
  const bodyOnly = countText(preamble.join("\n"), opts);
  const documentTotal = bodyOnly + headings.reduce((acc, h) => acc + h.ownCount, 0);
  return { headings, documentTotal };
}

// i18n.ts
var EN = {
  panelTitle: "Word Count Outline",
  ribbonTooltip: "Word Count Outline",
  cmdOpen: "Open the word-count outline panel",
  emptyNoFile: "Open a Markdown note to see the word-count outline.",
  emptyNoHeadings: "This note has no headings (H1\u2013H6).",
  untitled: "(untitled)",
  docTotal: (n) => `${n} words total`,
  tipCollapseAll: "Collapse all",
  tipExpandAll: "Expand all",
  tipAutoOn: "This file: auto-scroll to bottom on open (click to turn off)",
  tipAutoOff: "This file: auto-scroll to bottom on open (click to turn on)",
  setLangName: "Interface language",
  setLangDesc: `Language for this plugin's UI. "Auto" follows Obsidian's own language setting. Command and ribbon labels update after a reload.`,
  optAuto: "Auto (follow Obsidian)",
  setScopeName: "Counting scope",
  setScopeDesc: "Whether each heading's count includes all of its sub-sections, or only its own text up to the next heading.",
  optTotal: "Include sub-sections (an H1 includes everything beneath it)",
  optOwn: "Own section only (excludes sub-sections)",
  setPunctName: "Count Chinese punctuation",
  setPunctDesc: "When on, Chinese punctuation (\uFF0C\u3002\u3001\uFF01\uFF1F\u300C\u300Detc.) each counts as 1. Chinese characters are always counted one-by-one regardless of this.",
  setExCodeName: "Exclude code blocks",
  setExCodeDesc: "Do not count text inside ``` fenced code blocks.",
  setExInlineName: "Exclude inline code",
  setExInlineDesc: "Do not count text inside `inline code`.",
  setDepthName: "Show headings down to level",
  setDepthDesc: "Only show headings down to this level (1 = H1 only, 6 = show all).",
  setShowTotalName: "Show whole-note total",
  setShowTotalDesc: "Show the note's total word count at the top of the panel.",
  setAutoScrollName: "Auto-scroll to bottom on open (per file)",
  setAutoScrollDesc: "This is a per-file setting: in the outline panel, click the down button (\u2304\u2304) to mark the current note as auto-scroll-to-bottom. Only marked notes do this; others behave normally.",
  autoListLabel: "Files currently set to auto-scroll to bottom:",
  removeBtn: "Remove",
  setHelpName: "Help",
  setHelpDesc: "Show the usage guide again.",
  setHelpBtn: "Open guide",
  cmdShowHelp: "Show Heading Word Count help",
  helpTitle: "Welcome to Heading Word Count",
  helpIntro: "This plugin shows a live word count next to every heading (H1\u2013H6) in your notes. Here's how to use it.",
  helpSections: [
    {
      heading: "Open the outline panel",
      lines: [
        'Click the list icon in the left ribbon, or run "Open the word-count outline panel" from the command palette (Ctrl/Cmd+P).'
      ]
    },
    {
      heading: "How counting works",
      lines: [
        "Chinese characters are always counted one by one.",
        "Chinese punctuation (\uFF0C\u3002\u3001\uFF01\uFF1F\u300C\u300Detc.) is NOT counted by default \u2014 turn it on in Settings if you want it.",
        "English text is counted by word, the normal way.",
        `Each heading's badge can show its own count, or the total including everything beneath it \u2014 switch this in Settings under "Counting scope".`
      ]
    },
    {
      heading: "Toolbar buttons",
      lines: [
        "The first button collapses or expands the whole outline (one button, click again to reverse). It's dimmed when the note has no nested headings to fold.",
        'The second button (\u2304\u2304) turns on "auto-scroll to bottom on open" for the current file only \u2014 handy for a daily log or journal you always want to jump straight to the bottom of.'
      ]
    },
    {
      heading: "Settings",
      lines: [
        "Open Settings \u2192 Community plugins \u2192 Heading Word Count to change the interface language, counting rules, how many heading levels to show, and to review or remove the list of auto-scroll files."
      ]
    },
    {
      heading: "Need this again later?",
      lines: [
        `Run the command "Show Heading Word Count help", or click the button in this plugin's settings tab.`
      ]
    }
  ]
};
var ZH = {
  panelTitle: "\u5B57\u6578\u5927\u7DB1",
  ribbonTooltip: "\u5B57\u6578\u5927\u7DB1",
  cmdOpen: "\u958B\u555F\u5B57\u6578\u5927\u7DB1\u9762\u677F",
  emptyNoFile: "\u958B\u555F\u4E00\u4EFD Markdown \u7B46\u8A18\u4EE5\u986F\u793A\u5B57\u6578\u5927\u7DB1\u3002",
  emptyNoHeadings: "\u9019\u4EFD\u7B46\u8A18\u6C92\u6709\u6A19\u984C (H1\u2013H6)\u3002",
  untitled: "(\u7121\u6A19\u984C)",
  docTotal: (n) => `\u5168\u6587 ${n} \u5B57`,
  tipCollapseAll: "\u5168\u90E8\u6536\u5408",
  tipExpandAll: "\u5168\u90E8\u5C55\u958B",
  tipAutoOn: "\u6B64\u6A94\u6848\uFF1A\u958B\u555F\u6642\u81EA\u52D5\u6372\u5230\u5E95\uFF08\u9EDE\u64CA\u95DC\u9589\uFF09",
  tipAutoOff: "\u6B64\u6A94\u6848\uFF1A\u958B\u555F\u6642\u81EA\u52D5\u6372\u5230\u5E95\uFF08\u9EDE\u64CA\u958B\u555F\uFF09",
  setLangName: "\u4ECB\u9762\u8A9E\u8A00",
  setLangDesc: "\u5916\u639B\u4ECB\u9762\u8981\u7528\u7684\u8A9E\u8A00\u3002\u300C\u81EA\u52D5\u300D\u6703\u8DDF\u96A8 Obsidian \u672C\u8EAB\u7684\u8A9E\u8A00\u8A2D\u5B9A\u3002\u6307\u4EE4\u8207\u529F\u80FD\u5340\u7684\u540D\u7A31\u6703\u5728\u91CD\u65B0\u8F09\u5165\u5F8C\u66F4\u65B0\u3002",
  optAuto: "\u81EA\u52D5\uFF08\u8DDF\u96A8 Obsidian\uFF09",
  setScopeName: "\u8A08\u7B97\u7BC4\u570D",
  setScopeDesc: "\u6BCF\u500B\u6A19\u984C\u7684\u5B57\u6578\u8981\u300C\u5305\u542B\u5E95\u4E0B\u6240\u6709\u5B50\u7AE0\u7BC0\u300D\uFF0C\u9084\u662F\u300C\u53EA\u7B97\u5230\u4E0B\u4E00\u500B\u6A19\u984C\u4E4B\u524D\u300D\u3002",
  optTotal: "\u542B\u5B50\u7AE0\u7BC0\uFF08H1 \u5305\u542B\u5176\u4E0B\u6240\u6709\u5167\u5BB9\uFF09",
  optOwn: "\u53EA\u7B97\u672C\u7BC0\uFF08\u4E0D\u542B\u5B50\u7AE0\u7BC0\uFF09",
  setPunctName: "\u8A08\u5165\u4E2D\u6587\u6A19\u9EDE\u7B26\u865F",
  setPunctDesc: "\u958B\u555F\u5F8C\uFF0C\u4E2D\u6587\u6A19\u9EDE\uFF08\uFF0C\u3002\u3001\uFF01\uFF1F\u300C\u300D\u7B49\uFF09\u4E5F\u6703\u8A08\u70BA 1 \u500B\u5B57\u3002\u4E2D\u6587\u65B9\u584A\u5B57\u4E00\u5F8B\u9010\u5B57\u8A08\u7B97\uFF0C\u4E0D\u53D7\u6B64\u9805\u5F71\u97FF\u3002",
  setExCodeName: "\u6392\u9664\u7A0B\u5F0F\u78BC\u5340\u584A",
  setExCodeDesc: "\u4E0D\u8A08\u7B97 ``` \u570D\u6B04\u7A0B\u5F0F\u78BC\u5340\u584A\u5167\u7684\u6587\u5B57\u3002",
  setExInlineName: "\u6392\u9664\u884C\u5167\u7A0B\u5F0F\u78BC",
  setExInlineDesc: "\u4E0D\u8A08\u7B97 `\u884C\u5167\u7A0B\u5F0F\u78BC` \u5167\u7684\u6587\u5B57\u3002",
  setDepthName: "\u986F\u793A\u5230\u7B2C\u5E7E\u5C64\u6A19\u984C",
  setDepthDesc: "\u53EA\u5728\u9762\u677F\u4E2D\u986F\u793A\u5230\u6307\u5B9A\u5C64\u7D1A\u7684\u6A19\u984C\uFF081 = \u53EA\u986F\u793A H1\uFF0C6 = \u5168\u90E8\u986F\u793A\uFF09\u3002",
  setShowTotalName: "\u986F\u793A\u5168\u6587\u7E3D\u5B57\u6578",
  setShowTotalDesc: "\u5728\u9762\u677F\u9802\u7AEF\u986F\u793A\u6574\u4EFD\u7B46\u8A18\u7684\u7E3D\u5B57\u6578\u3002",
  setAutoScrollName: "\u958B\u555F\u6642\u81EA\u52D5\u6372\u5230\u5E95\uFF08\u4F9D\u6A94\u6848\uFF09",
  setAutoScrollDesc: "\u6B64\u529F\u80FD\u662F\u300C\u9010\u6A94\u6848\u300D\u8A2D\u5B9A\uFF1A\u5728\u5B57\u6578\u5927\u7DB1\u9762\u677F\u9802\u7AEF\u9EDE\u300C\u2304\u2304\u300D\u6309\u9215\uFF0C\u628A\u76EE\u524D\u9019\u4EFD\u7B46\u8A18\u6A19\u8A18\u70BA\u300C\u958B\u555F\u6642\u81EA\u52D5\u6372\u5230\u5E95\u300D\u3002\u53EA\u6709\u88AB\u6A19\u8A18\u7684\u6A94\u6848\u6703\u9019\u6A23\uFF0C\u5176\u5B83\u6A94\u6848\u7167\u5E38\u3002",
  autoListLabel: "\u76EE\u524D\u5DF2\u6A19\u8A18\u81EA\u52D5\u6372\u5230\u5E95\u7684\u6A94\u6848\uFF1A",
  removeBtn: "\u79FB\u9664",
  setHelpName: "\u4F7F\u7528\u8AAA\u660E",
  setHelpDesc: "\u91CD\u65B0\u770B\u4E00\u6B21\u5916\u639B\u7684\u4F7F\u7528\u8AAA\u660E\u3002",
  setHelpBtn: "\u958B\u555F\u8AAA\u660E",
  cmdShowHelp: "\u986F\u793A Heading Word Count \u4F7F\u7528\u8AAA\u660E",
  helpTitle: "\u6B61\u8FCE\u4F7F\u7528 Heading Word Count",
  helpIntro: "\u9019\u500B\u5916\u639B\u6703\u5728\u4F60\u7B46\u8A18\u88E1\u6BCF\u500B\u6A19\u984C\uFF08H1\u2013H6\uFF09\u65C1\u908A\u5373\u6642\u986F\u793A\u5B57\u6578\u3002\u4EE5\u4E0B\u662F\u4F7F\u7528\u65B9\u5F0F\u3002",
  helpSections: [
    {
      heading: "\u958B\u555F\u5927\u7DB1\u9762\u677F",
      lines: [
        "\u9EDE\u5DE6\u5074\u529F\u80FD\u5340\u7684\u6E05\u55AE\u5716\u793A\uFF0C\u6216\u7528\u6307\u4EE4\u9762\u677F\uFF08Ctrl/Cmd+P\uFF09\u57F7\u884C\u300C\u958B\u555F\u5B57\u6578\u5927\u7DB1\u9762\u677F\u300D\u3002"
      ]
    },
    {
      heading: "\u8A08\u7B97\u898F\u5247",
      lines: [
        "\u4E2D\u6587\u5B57\u4E00\u5F8B\u9010\u5B57\u8A08\u7B97\u3002",
        "\u4E2D\u6587\u6A19\u9EDE\uFF08\uFF0C\u3002\u3001\uFF01\uFF1F\u300C\u300D\u7B49\uFF09\u9810\u8A2D\u4E0D\u8A08\u5165\uFF0C\u53EF\u4EE5\u5230\u8A2D\u5B9A\u88E1\u6253\u958B\u3002",
        "\u82F1\u6587\u7167\u4E00\u822C\u65B9\u5F0F\u9010\u5B57\uFF08word\uFF09\u8A08\u7B97\u3002",
        "\u6BCF\u500B\u6A19\u984C\u65C1\u7684\u6578\u5B57\uFF0C\u53EF\u4EE5\u986F\u793A\u300C\u53EA\u7B97\u672C\u7BC0\u300D\u6216\u300C\u542B\u6240\u6709\u5B50\u7AE0\u7BC0\u300D\u2014\u2014\u5728\u8A2D\u5B9A\u7684\u300C\u8A08\u7B97\u7BC4\u570D\u300D\u88E1\u5207\u63DB\u3002"
      ]
    },
    {
      heading: "\u5DE5\u5177\u5217\u6309\u9215",
      lines: [
        "\u7B2C\u4E00\u9846\u6309\u9215\u662F\u300C\u5168\u90E8\u6536\u5408\uFF0F\u5168\u90E8\u5C55\u958B\u300D\uFF0C\u540C\u4E00\u9846\u5FAA\u74B0\u5207\u63DB\u5373\u53EF\u3002\u5982\u679C\u9019\u7BC7\u7B46\u8A18\u6C92\u6709\u5DE2\u72C0\u6A19\u984C\u53EF\u6536\u5408\uFF0C\u6309\u9215\u6703\u8B8A\u6697\u3002",
        "\u7B2C\u4E8C\u9846\u6309\u9215\uFF08\u2304\u2304\uFF09\u662F\u300C\u958B\u555F\u6642\u81EA\u52D5\u6372\u5230\u5E95\u300D\uFF0C\u53EA\u91DD\u5C0D\u76EE\u524D\u9019\u500B\u6A94\u6848\u2014\u2014\u5F88\u9069\u5408\u50CF\u65E5\u8A18\u3001\u6D41\u6C34\u5E33\u9019\u7A2E\u4F60\u7E3D\u662F\u60F3\u76F4\u63A5\u8DF3\u5230\u6700\u5F8C\u9762\u7684\u7B46\u8A18\u3002"
      ]
    },
    {
      heading: "\u8A2D\u5B9A",
      lines: [
        "\u5230\u300C\u8A2D\u5B9A \u2192 \u793E\u7FA4\u5916\u639B \u2192 Heading Word Count\u300D\u53EF\u4EE5\u8ABF\u6574\u4ECB\u9762\u8A9E\u8A00\u3001\u8A08\u7B97\u898F\u5247\u3001\u8981\u986F\u793A\u5230\u7B2C\u5E7E\u5C64\u6A19\u984C\uFF0C\u4E5F\u80FD\u67E5\u770B\u6216\u79FB\u9664\u76EE\u524D\u8A2D\u5B9A\u81EA\u52D5\u6372\u5230\u5E95\u7684\u6A94\u6848\u6E05\u55AE\u3002"
      ]
    },
    {
      heading: "\u4E4B\u5F8C\u60F3\u518D\u770B\u4E00\u6B21\uFF1F",
      lines: [
        "\u96A8\u6642\u57F7\u884C\u6307\u4EE4\u300C\u986F\u793A Heading Word Count \u4F7F\u7528\u8AAA\u660E\u300D\uFF0C\u6216\u5230\u5916\u639B\u8A2D\u5B9A\u9801\u6309\u4E0B\u8AAA\u660E\u6309\u9215\u5373\u53EF\u3002"
      ]
    }
  ]
};
function detectObsidianLang() {
  try {
    const l = window.localStorage.getItem("language") || "";
    return l.toLowerCase().startsWith("zh") ? "zh" : "en";
  } catch (e) {
    return "en";
  }
}
function getStrings(pref) {
  const lang = pref === "auto" ? detectObsidianLang() : pref;
  return lang === "zh" ? ZH : EN;
}

// main.ts
var VIEW_TYPE = "heading-word-count-outline";
var DEFAULT_SETTINGS = {
  ...DEFAULT_COUNT_OPTIONS,
  countMode: "total",
  showDocumentTotal: true,
  maxDepth: 6,
  autoScrollFiles: [],
  uiLanguage: "auto",
  lastSeenVersion: ""
};
function buildTree(headings) {
  const roots = [];
  const stack = [];
  for (const h of headings) {
    const node = { ...h, children: [] };
    while (stack.length && stack[stack.length - 1].level >= h.level) {
      stack.pop();
    }
    if (stack.length)
      stack[stack.length - 1].children.push(node);
    else
      roots.push(node);
    stack.push(node);
  }
  return roots;
}
function collectParentLines(nodes, out) {
  for (const n of nodes) {
    if (n.children.length) {
      out.push(n.line);
      collectParentLines(n.children, out);
    }
  }
}
var HelpModal = class extends import_obsidian.Modal {
  constructor(app, t) {
    super(app);
    this.t = t;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("hwc-help-modal");
    contentEl.createEl("h2", { text: this.t.helpTitle });
    contentEl.createEl("p", { text: this.t.helpIntro });
    for (const section of this.t.helpSections) {
      contentEl.createEl("h3", { text: section.heading });
      for (const line of section.lines) {
        contentEl.createEl("p", { text: line });
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var HeadingWordCountPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    const isFirstRun = !this.settings.lastSeenVersion;
    if (this.settings.lastSeenVersion !== this.manifest.version) {
      this.settings.lastSeenVersion = this.manifest.version;
      await this.saveData(this.settings);
    }
    this.registerView(VIEW_TYPE, (leaf) => new HeadingWordCountView(leaf, this));
    this.addRibbonIcon("list-ordered", this.t.ribbonTooltip, () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-outline",
      name: this.t.cmdOpen,
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "show-help",
      name: this.t.cmdShowHelp,
      callback: () => {
        new HelpModal(this.app, this.t).open();
      }
    });
    this.addSettingTab(new HeadingWordCountSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.refreshViews())
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        this.refreshViews();
        if (file && this.settings.autoScrollFiles.includes(file.path)) {
          void this.autoScrollOnOpen(file);
        }
      })
    );
    const debouncedRefresh = (0, import_obsidian.debounce)(() => this.refreshViews(), 400, false);
    this.registerEvent(
      this.app.workspace.on("editor-change", () => debouncedRefresh())
    );
    this.app.workspace.onLayoutReady(() => {
      this.refreshViews();
      if (isFirstRun) {
        new HelpModal(this.app, this.t).open();
      }
    });
  }
  onunload() {
  }
  applyLang() {
    this.t = getStrings(this.settings.uiLanguage);
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data != null ? data : {});
    if (!Array.isArray(this.settings.autoScrollFiles)) {
      this.settings.autoScrollFiles = [];
    }
    this.applyLang();
  }
  async saveSettings() {
    this.applyLang();
    await this.saveData(this.settings);
    this.refreshViews();
  }
  /**
   * Scrolls the editor for `file` to the bottom right after it was opened.
   *
   * On mobile especially, Obsidian frequently hands the newly-opened file a
   * "deferred" leaf: `leaf.view` is a placeholder, not the real
   * MarkdownView, until it is explicitly loaded. Scrolling (or even reading
   * `.editor`) on a leaf in that state silently does nothing, which is why
   * this feature would work on desktop but not on phones. We locate the
   * leaf that now holds this file, force it to finish loading if it is
   * deferred, and only then touch the editor.
   */
  async autoScrollOnOpen(file) {
    var _a;
    let leaf = this.app.workspace.getLeavesOfType("markdown").find(
      (l) => {
        var _a2;
        return ((_a2 = l.getViewState().state) == null ? void 0 : _a2.file) === file.path;
      }
    );
    if (!leaf)
      leaf = (_a = this.app.workspace.getMostRecentLeaf()) != null ? _a : void 0;
    if (!leaf)
      return;
    if (leaf.isDeferred) {
      await leaf.loadIfDeferred();
    }
    window.setTimeout(() => {
      const active = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (active && active.file && active.file.path === file.path) {
        this.scrollEditorToBottom(active);
        return;
      }
      const view = leaf.view;
      if (view instanceof import_obsidian.MarkdownView && view.file && view.file.path === file.path) {
        this.scrollEditorToBottom(view);
      }
    }, 80);
  }
  scrollEditorToBottom(view) {
    const editor = view.editor;
    const last = editor.lastLine();
    editor.setCursor({ line: last, ch: editor.getLine(last).length });
    editor.scrollIntoView(
      { from: { line: last, ch: 0 }, to: { line: last, ch: 0 } },
      true
    );
  }
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof HeadingWordCountView)
        view.render();
    });
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (!right)
        return;
      leaf = right;
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    await workspace.revealLeaf(leaf);
  }
};
var HeadingWordCountView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    /** Collapsed heading lines, keyed by file path. */
    this.collapsed = /* @__PURE__ */ new Map();
    this.currentFile = null;
    this.currentRoots = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.plugin.t.panelTitle;
  }
  getIcon() {
    return "list-ordered";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  getCollapsedSet(path) {
    let s = this.collapsed.get(path);
    if (!s) {
      s = /* @__PURE__ */ new Set();
      this.collapsed.set(path, s);
    }
    return s;
  }
  getActiveMarkdownFile() {
    const active = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (active && active.file)
      return active.file;
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const v = leaf.view;
      if (v instanceof import_obsidian.MarkdownView && v.file)
        return v.file;
    }
    return null;
  }
  render() {
    const container = this.contentEl;
    container.addClass("hwc-view");
    const file = this.getActiveMarkdownFile();
    if (!file) {
      container.empty();
      container.createDiv({
        cls: "hwc-empty",
        text: this.plugin.t.emptyNoFile
      });
      return;
    }
    const activeMd = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeMd && activeMd.file === file) {
      this.renderContent(file, activeMd.editor.getValue());
    } else {
      this.app.vault.cachedRead(file).then((content) => {
        this.renderContent(file, content);
      });
    }
  }
  renderContent(file, content) {
    const container = this.contentEl;
    container.empty();
    this.currentFile = file;
    const t = this.plugin.t;
    const data = analyzeDocument(content, this.plugin.settings);
    const s = this.plugin.settings;
    const visible = data.headings.filter((h) => h.level <= s.maxDepth);
    this.currentRoots = buildTree(visible);
    const collapsedSet = this.getCollapsedSet(file.path);
    const parentLines = [];
    collectParentLines(this.currentRoots, parentLines);
    const allCollapsed = parentLines.length > 0 && parentLines.every((l) => collapsedSet.has(l));
    const header = container.createDiv({ cls: "hwc-header" });
    const titleRow = header.createDiv({ cls: "hwc-titlerow" });
    titleRow.createDiv({ cls: "hwc-filename", text: file.basename });
    const toolbar = titleRow.createDiv({ cls: "hwc-toolbar" });
    const hasFoldable = parentLines.length > 0;
    const foldBtn = toolbar.createDiv({
      cls: "hwc-btn" + (hasFoldable ? "" : " hwc-btn-disabled")
    });
    (0, import_obsidian.setIcon)(foldBtn, allCollapsed ? "chevrons-up-down" : "chevrons-down-up");
    foldBtn.setAttribute(
      "aria-label",
      allCollapsed ? t.tipExpandAll : t.tipCollapseAll
    );
    foldBtn.addEventListener("click", () => {
      if (!hasFoldable)
        return;
      if (allCollapsed)
        this.expandAll();
      else
        this.collapseAll();
    });
    const autoOn = s.autoScrollFiles.includes(file.path);
    const scrollBtn = toolbar.createDiv({
      cls: "hwc-btn" + (autoOn ? " is-active" : "")
    });
    (0, import_obsidian.setIcon)(scrollBtn, "chevrons-down");
    scrollBtn.setAttribute("aria-label", autoOn ? t.tipAutoOn : t.tipAutoOff);
    scrollBtn.addEventListener("click", () => void this.toggleAutoScroll(file));
    if (s.showDocumentTotal) {
      header.createDiv({
        cls: "hwc-doctotal",
        text: t.docTotal(formatCount(data.documentTotal))
      });
    }
    if (visible.length === 0) {
      container.createDiv({
        cls: "hwc-empty",
        text: t.emptyNoHeadings
      });
      return;
    }
    const list = container.createDiv({ cls: "hwc-list" });
    this.renderNodes(this.currentRoots, list, collapsedSet, file);
  }
  renderNodes(nodes, listEl, collapsedSet, file) {
    const s = this.plugin.settings;
    const t = this.plugin.t;
    for (const node of nodes) {
      const hasChildren = node.children.length > 0;
      const isCollapsed = collapsedSet.has(node.line);
      const row = listEl.createDiv({ cls: `hwc-row hwc-h${node.level}` });
      row.style.paddingLeft = `${(node.level - 1) * 14 + 4}px`;
      const fold = row.createSpan({ cls: "hwc-fold" });
      if (hasChildren) {
        (0, import_obsidian.setIcon)(fold, isCollapsed ? "chevron-right" : "chevron-down");
        fold.addEventListener("click", (e) => {
          e.stopPropagation();
          if (collapsedSet.has(node.line))
            collapsedSet.delete(node.line);
          else
            collapsedSet.add(node.line);
          this.render();
        });
      } else {
        fold.addClass("hwc-fold-empty");
      }
      const count = s.countMode === "total" ? node.totalCount : node.ownCount;
      row.createSpan({ cls: "hwc-title", text: node.title || t.untitled });
      row.createSpan({ cls: "hwc-badge", text: formatCount(count) });
      row.addEventListener("click", () => this.revealHeading(file, node.line));
      if (hasChildren && !isCollapsed) {
        this.renderNodes(node.children, listEl, collapsedSet, file);
      }
    }
  }
  collapseAll() {
    if (!this.currentFile)
      return;
    const set = this.getCollapsedSet(this.currentFile.path);
    const lines = [];
    collectParentLines(this.currentRoots, lines);
    lines.forEach((l) => set.add(l));
    this.render();
  }
  expandAll() {
    if (!this.currentFile)
      return;
    this.getCollapsedSet(this.currentFile.path).clear();
    this.render();
  }
  async toggleAutoScroll(file) {
    const arr = this.plugin.settings.autoScrollFiles;
    const idx = arr.indexOf(file.path);
    let turnedOn = false;
    if (idx >= 0)
      arr.splice(idx, 1);
    else {
      arr.push(file.path);
      turnedOn = true;
    }
    await this.plugin.saveSettings();
    if (turnedOn) {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view && view.file && view.file.path === file.path) {
        this.plugin.scrollEditorToBottom(view);
      }
    }
  }
  revealHeading(file, line) {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    let target = null;
    for (const leaf of leaves) {
      const v = leaf.view;
      if (v instanceof import_obsidian.MarkdownView && v.file === file) {
        target = leaf;
        break;
      }
    }
    const open = target ? Promise.resolve(target) : this.app.workspace.getLeaf(false).openFile(file).then(() => {
      return this.app.workspace.getMostRecentLeaf();
    });
    void Promise.resolve(open).then((leaf) => {
      if (!leaf)
        return;
      void this.app.workspace.revealLeaf(leaf);
      const view = leaf.view;
      if (view instanceof import_obsidian.MarkdownView) {
        const editor = view.editor;
        editor.setCursor({ line, ch: 0 });
        editor.scrollIntoView(
          { from: { line, ch: 0 }, to: { line, ch: 0 } },
          true
        );
        editor.focus();
      }
    });
  }
};
function formatCount(n) {
  return n.toLocaleString("en-US");
}
var HeadingWordCountSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const t = this.plugin.t;
    new import_obsidian.Setting(containerEl).setName(t.setLangName).setDesc(t.setLangDesc).addDropdown(
      (d) => d.addOption("auto", t.optAuto).addOption("zh", "\u4E2D\u6587").addOption("en", "English").setValue(this.plugin.settings.uiLanguage).onChange(async (v) => {
        this.plugin.settings.uiLanguage = v;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setScopeName).setDesc(t.setScopeDesc).addDropdown(
      (d) => d.addOption("total", t.optTotal).addOption("own", t.optOwn).setValue(this.plugin.settings.countMode).onChange(async (v) => {
        this.plugin.settings.countMode = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setPunctName).setDesc(t.setPunctDesc).addToggle(
      (tg) => tg.setValue(this.plugin.settings.countChinesePunctuation).onChange(async (v) => {
        this.plugin.settings.countChinesePunctuation = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setExCodeName).setDesc(t.setExCodeDesc).addToggle(
      (tg) => tg.setValue(this.plugin.settings.excludeCodeBlocks).onChange(async (v) => {
        this.plugin.settings.excludeCodeBlocks = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setExInlineName).setDesc(t.setExInlineDesc).addToggle(
      (tg) => tg.setValue(this.plugin.settings.excludeInlineCode).onChange(async (v) => {
        this.plugin.settings.excludeInlineCode = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setDepthName).setDesc(t.setDepthDesc).addSlider(
      (sl) => sl.setLimits(1, 6, 1).setValue(this.plugin.settings.maxDepth).onChange(async (v) => {
        this.plugin.settings.maxDepth = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setShowTotalName).setDesc(t.setShowTotalDesc).addToggle(
      (tg) => tg.setValue(this.plugin.settings.showDocumentTotal).onChange(async (v) => {
        this.plugin.settings.showDocumentTotal = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setHelpName).setDesc(t.setHelpDesc).addButton(
      (b) => b.setButtonText(t.setHelpBtn).onClick(() => {
        new HelpModal(this.app, t).open();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.setAutoScrollName).setDesc(t.setAutoScrollDesc);
    if (this.plugin.settings.autoScrollFiles.length > 0) {
      const list = containerEl.createDiv({ cls: "hwc-settings-filelist" });
      list.createEl("div", {
        text: t.autoListLabel,
        cls: "setting-item-description"
      });
      for (const p of [...this.plugin.settings.autoScrollFiles]) {
        const row = new import_obsidian.Setting(list).setName(p);
        row.addButton(
          (b) => b.setButtonText(t.removeBtn).onClick(async () => {
            const arr = this.plugin.settings.autoScrollFiles;
            const i = arr.indexOf(p);
            if (i >= 0)
              arr.splice(i, 1);
            await this.plugin.saveSettings();
            this.display();
          })
        );
      }
    }
  }
};
